"""initial tables

Revision ID: de8aef88c056
Revises: 
Create Date: 2026-05-12 22:21:42.977859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8aef88c056'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('election_type', sa.Enum('general', 'state', 'local', 'by_election', name='electiontype'), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'ongoing', 'completed', name='electionstatus'), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('constituency', sa.String(length=200), nullable=True),
    sa.Column('total_voters', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_id'), 'elections', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('party', sa.Enum('bjp', 'inc', 'aap', 'sp', 'tmc', 'other', name='politicalparty'), nullable=False),
    sa.Column('status', sa.Enum('active', 'withdrawn', 'disqualified', name='candidatestatus'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('constituency', sa.String(length=200), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_election_id'), 'candidates', ['election_id'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('credibility', sa.Enum('credible', 'misleading', 'fake', name='credibilitylabel'), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('fake_news_label', sa.String(length=50), nullable=True),
    sa.Column('fake_news_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_election_id'), 'news_articles', ['election_id'], unique=False)
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_election_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_election_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_elections_id'), table_name='elections')
    op.drop_table('elections')
    # ### end Alembic commands ###
