# app/models/election.py

from pydantic import BaseModel, Field
from typing import Optional, List
from enum import Enum
from datetime import date


# --- Enum for Election Type ---
# Enums restrict a field to a fixed set of allowed values.
# This prevents bad data like type="banana" from entering the system.
class ElectionType(str, Enum):
    general = "general"
    state = "state"
    local = "local"
    by_election = "by_election"


# --- Enum for Election Status ---
class ElectionStatus(str, Enum):
    upcoming = "upcoming"
    ongoing = "ongoing"
    completed = "completed"


# --- Base Model ---
# Shared fields used across Create and Response models.
# We follow the DRY principle: Don't Repeat Yourself.
class ElectionBase(BaseModel):
    name: str = Field(
        ...,
        min_length=3,
        max_length=200,
        description="Full name of the election",
        examples=["2024 Indian General Election"],
    )
    country: str = Field(
        ...,
        min_length=2,
        max_length=100,
        description="Country where the election is held",
        examples=["India"],
    )
    election_type: ElectionType = Field(
        ...,
        description="Type of election",
    )
    election_date: date = Field(
        ...,
        description="Scheduled date of the election (YYYY-MM-DD)",
    )
    description: Optional[str] = Field(
        None,
        max_length=1000,
        description="Optional context about the election",
    )


# --- Create Model ---
# This is what the API *accepts* as input when creating an election.
# Inherits all fields from ElectionBase.
class ElectionCreate(ElectionBase):
    pass


# --- Response Model ---
# This is what the API *returns* to the client.
# It adds fields that are generated by the server (id, status).
class ElectionResponse(ElectionBase):
    id: int = Field(..., description="Auto-assigned unique identifier")
    status: ElectionStatus = Field(
        default=ElectionStatus.upcoming,
        description="Current status of the election",
    )

    class Config:
        # Allows Pydantic to work seamlessly with ORM objects later
        # when we integrate PostgreSQL in a future step
        from_attributes = True




class ElectionSummaryResponse(BaseModel):
    """
    Returned by POST /elections/{id}/summarize
    Contains the AI-generated briefing for a single election.
    """
    election_id:       int
    election_name:     str
    summary:           str
    key_topics:        List[str]
    overall_sentiment: str
    model_used:        str
    raw_response:      str